# Generated by Django 5.2.4 on 2025-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_id', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('turbidity_ntu', models.FloatField()),
                ('do_mg_l', models.FloatField()),
                ('ec_us_cm', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
